version: 2.1
orbs:
  shellcheck: circleci/shellcheck@2.0.0
workflows:
  my_workflow:
    jobs:
      - shellcheck/check:
          dir: ./
          exclude: SC2148,SC2034,SC2016,SC2059,SC2007,SC2162,SC2220,SC1091